---
--- Generated by Luanalysis
--- Created by CHEN.
--- DateTime: 2022/10/12 17:37
---

---秒杀券id
local voucherId = ARGV[1]
--用户id
local userId = ARGV[2]
--订单id
local id = ARGV[3]
--服务器当前时间（epoch seconds）
local now = tonumber(ARGV[4])

--库存key
local stockKey = 'seckill:stock:' .. voucherId
--订单key（已下单用户集合）
local orderKey = 'seckill:order:' .. voucherId
-- userId -> orderId（重复下单时返回原订单号）
local orderIdMapKey = 'seckill:order:id:' .. voucherId
-- 用户侧 processing 集合（mine 列表可合并）
local processingKey = 'seckill:processing:' .. userId
-- 按订单 id 查 owner（结果查询 PROCESSING）
local acceptKey = 'seckill:accept:' .. id
--活动时间窗（epoch seconds）
local beginKey = 'seckill:begin:' .. voucherId
local endKey = 'seckill:end:' .. voucherId

--活动时间元数据缺失则拒绝（不开放购买）
local beginTime = tonumber(redis.call('get', beginKey))
local endTime = tonumber(redis.call('get', endKey))
if (beginTime == nil or endTime == nil) then
    return 3
end

--不在 [begin, end] 内
if (now < beginTime or now > endTime) then
    return 3
end

--库存是否充足
--库存不足（含 stock key 缺失）
local stock = tonumber(redis.call('get', stockKey))
if (stock == nil or stock <= 0) then
    return 1
end

--判断用户是否下单
--存在用户 禁止重复下单（Java 侧 HGET orderIdMap 返回原 orderId）
if (tonumber(redis.call('sismember', orderKey, userId)) == 1) then
    return 2
end

--扣减库存
redis.call('incrby', stockKey, -1)
--下单（保存用户 + 原订单号映射）
redis.call('sadd', orderKey, userId)
redis.call('hset', orderIdMapKey, userId, id)
redis.call('sadd', processingKey, id)
-- accept 记录 TTL 24h：Redis 宕机于 MySQL 落库前仍可能丢（见 docs）
redis.call('setex', acceptKey, 86400, userId)
--发送消息
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', id)
return 0
